= LaTeX Docker image

Docker container images for running LaTeX (TexLive) compilations. The image is based on Debian slim with a minimal set of LaTeX packages. The image size is reasonably chunky – 2.17GB – but it covers most use cases for compiling PDFs from LaTeX documents using `pdflatex`.

See the https://hub.docker.com/r/kieranpotts/latex[Docker Hub repository] for usage instructions. Also see my https://github.com/kieranpotts/resume[résumé] for example usage.

The following documentation is for the maintainers of this project.

== Documentation

=== Requirements

* Docker
* Make
* Git

=== Prerequisites

Make the `run/*` scripts executable:

[source,sh]
----
chmod +x run/*
----

=== Building images locally

[source,sh]
----
make build
----

This builds an image from `./src/Dockerfile`. The image will be added to your locally running instance of Docker.

Verify the built image with this command:

[source,sh]
----
docker images kieranpotts/latex:latest
----

To build only one variant:

[source,sh]
----
docker build -t kieranpotts/latex:texlive-full -f src/texlive-full/Dockerfile .
----

You can verify the build with:

[source,sh]
----
docker images kieranpotts/latex:texlive-full
----

=== Image variants

One image variant is available at this time.

* `texlive-full` — Ubuntu 24.04 LTS base with the full TexLive package. This is the most commonly used TexLive package and is suitable for most use cases. However, it's a large package. The image size is 2.64GB, and disk usage of a running container is 8.75GB.

Other variants will be added in the future.


Docker container image for running LaTeX compilations.

''''

Copyright © 2025-present Kieran Potts, link:./LICENSE.txt[MIT license]
