#!/usr/bin/env sh
set -e

dockerfile="$(dirname "$0")/../src/Dockerfile"
image="kieranpotts/latex:latest"

echo "Building ${image}..."
docker build --tag "${image}" --file "${dockerfile}" .

echo "Done."
